<?php

return [
    'scope_types' => [
        'global',
        'region',
        'venue',
        'project',
        'hub',
        'partner',
        'campaign',
        'display_network',
        'team',
    ],

    'roles' => [
        'super_admin' => [
            'group' => 'exploria_team',
            'label' => 'ادمین اصلی کل اکسپلوریا',
            'scope' => 'global',
            'reports_to' => null,
            'responsibilities' => [
                'Own platform governance, tenant policy, critical approvals, and final production readiness.',
                'Review regional, project, sponsor, hub, display, reward, and campaign performance.',
                'Resolve escalations that cross regional, venue, hub, sponsor, or financial boundaries.',
            ],
            'daily_operations' => [
                'Review global health dashboard, incidents, approvals, and blocked campaign actions.',
                'Check sponsor, display, reward, and partner exceptions that need executive approval.',
                'Confirm the daily rollout priorities with regional and project admins.',
                'Record decisions, risks, and next-day priorities in the operating log.',
            ],
        ],
        'regional_admin' => [
            'group' => 'exploria_team',
            'label' => 'ادمین منطقه‌ای',
            'scope' => 'region',
            'reports_to' => 'super_admin',
            'responsibilities' => [
                'Run the Exploria operation for one province or commercial region.',
                'Approve and supervise venues, project admins, field operators, sponsors, and regional reporting.',
                'Escalate policy, financial, legal, or cross-region issues to the super admin.',
            ],
            'daily_operations' => [
                'Review active venues, campaign status, staffing coverage, and regional alerts.',
                'Approve or reject regional partner, sponsor, and campaign requests within policy.',
                'Follow up with project admins on delayed missions, display slots, and field issues.',
                'Send a regional summary with blockers, KPIs, and tomorrow priorities.',
            ],
        ],
        'project_admin' => [
            'group' => 'exploria_team',
            'label' => 'مدیر پروژه مکانی اکسپلوریا',
            'scope' => 'venue',
            'reports_to' => 'regional_admin',
            'responsibilities' => [
                'Operate one or more contracted venue projects such as EcoPark, Milad Tower, or Eram.',
                'Coordinate venue executives, hub managers, field operators, display managers, and support assistants.',
                'Keep local campaign data, QR points, hub readiness, display inventory, and partner onboarding current.',
            ],
            'daily_operations' => [
                'Check venue readiness, open incidents, staffing, QR touchpoints, and active campaign timeline.',
                'Review hub, shop, sponsor, and display requests for the assigned venue.',
                'Confirm field operator assignments and unresolved visitor support cases.',
                'Close the day with venue KPIs, risks, and required regional decisions.',
            ],
        ],
        'field_operator' => [
            'group' => 'exploria_team',
            'label' => 'مجری میدانی کمپین',
            'scope' => 'campaign',
            'reports_to' => 'project_admin',
            'responsibilities' => [
                'Run campaign operations on site and validate that visitor touchpoints work in the real venue.',
                'Report QR, signage, reward redemption, crowd, device, and partner execution issues.',
                'Support mission execution without changing commercial or governance settings.',
            ],
            'daily_operations' => [
                'Inspect assigned touchpoints, QR codes, route signs, and reward desks before visitor traffic starts.',
                'Log field issues with photo, location, urgency, and owner.',
                'Assist partners, hub managers, and visitor helpers during campaign peaks.',
                'Submit end-of-day execution notes, attendance, resolved issues, and unresolved risks.',
            ],
        ],
        'treasure_assistant' => [
            'group' => 'exploria_team',
            'label' => 'یاریگر کاشفان گنج',
            'scope' => 'campaign',
            'reports_to' => 'field_operator',
            'responsibilities' => [
                'Guide visitors, families, and teams through treasure discovery and campaign participation.',
                'Help with check-in, QR scanning, mission guidance, queue support, and simple issue reporting.',
                'Escalate fraud, safety, technical, or reward problems to field operators.',
            ],
            'daily_operations' => [
                'Prepare visitor support station, printed guidance, and QR help materials.',
                'Help participants start missions and understand team or family participation rules.',
                'Record common visitor questions, failed scans, and support incidents.',
                'Hand over unresolved visitor issues and feedback at shift end.',
            ],
        ],
        'display_ads_manager' => [
            'group' => 'exploria_team',
            'label' => 'مدیر تبلیغات و نمایشگرها',
            'scope' => 'display_network',
            'reports_to' => 'project_admin',
            'responsibilities' => [
                'Schedule, monitor, and reconcile advertising on fixed and mobile display devices.',
                'Validate creative format, placement priority, timing, venue rules, and playback status.',
                'Coordinate sponsor, partner, hub, and campaign display needs with admin approval rules.',
            ],
            'daily_operations' => [
                'Review display device health, scheduled placements, conflicts, and failed playback telemetry.',
                'Prepare the next day ad schedule and resolve priority clashes.',
                'Confirm approved sponsor and partner campaigns are assigned to correct devices and time slots.',
                'Export playback exceptions and billing-relevant evidence for admin review.',
            ],
        ],
        'venue_executive' => [
            'group' => 'external_partner',
            'label' => 'مدیر مکان',
            'scope' => 'venue',
            'reports_to' => 'project_admin',
            'responsibilities' => [
                'Represent the operating venue and supervise local business, safety, and execution constraints.',
                'Review venue-level campaign calendar, hub performance, partner participation, and visitor impact.',
                'Coordinate with Exploria project admin without accessing unrelated venues.',
            ],
            'daily_operations' => [
                'Review today campaign schedule, visitor flow, venue notices, and operational restrictions.',
                'Check hub manager summaries and urgent venue requests.',
                'Approve local execution adjustments that affect venue operations.',
                'Share venue feedback and next-day constraints with the project admin.',
            ],
        ],
        'ravaq_manager' => [
            'group' => 'external_partner',
            'label' => 'مدیر رواق / زون تجاری',
            'scope' => 'hub',
            'reports_to' => 'venue_executive',
            'responsibilities' => [
                'زون تجاری، رواق یا خوشه واحدهای تجاری یک مکان را مدیریت می‌کند.',
                'فروشگاه‌ها، پیشنهادها، موجودی پاداش، تبلیغات محلی و آمادگی واحدها را در محدوده خود پایش می‌کند.',
                'درخواست‌های فروشگاه و اسپانسر داخلی رواق را پیش از ارسال به مدیر مکان یا اکسپلوریا مرتب می‌کند.',
            ],
            'daily_operations' => [
                'وضعیت واحدهای رواق، پیشنهادهای در انتظار، موجودی پاداش و تبلیغات محلی را بررسی کند.',
                'واحدهای کم‌آمادگی یا دارای مشکل تحویل را پیگیری کند.',
                'پیشنهادهای قابل تایید در سطح رواق را تایید، رد یا برای بررسی بالاتر ارجاع دهد.',
                'گزارش کوتاه رواق را برای مدیر مکان و مدیر پروژه اکسپلوریا ارسال کند.',
            ],
        ],
        'hub_manager' => [
            'group' => 'external_partner',
            'label' => 'مدیر هاب',
            'scope' => 'hub',
            'reports_to' => 'venue_executive',
            'responsibilities' => [
                'Manage a specific hub such as ravaq, science, education, culture, food, or commerce.',
                'Supervise shops, internal sponsors, local offers, reward readiness, and hub display placements.',
                'Approve or comment on hub-scoped partner offers and advertising where policy allows.',
            ],
            'daily_operations' => [
                'Review hub dashboard, partner status, reward inventory, pending ads, and display schedule.',
                'Follow up with shops or units that have low readiness or unresolved redemptions.',
                'Approve, reject, or escalate hub-scoped offers and advertising requests.',
                'Send hub summary to venue executive and Exploria project admin.',
            ],
        ],
        'shop_manager' => [
            'group' => 'external_partner',
            'label' => 'مدیر فروشگاه / واحد شریک',
            'scope' => 'partner',
            'reports_to' => 'hub_manager',
            'responsibilities' => [
                'Manage one shop, food unit, cultural unit, commercial unit, or service partner account.',
                'Maintain profile, offers, rewards, redemption codes, inventory, and partner advertising requests.',
                'Serve visitors according to approved campaign and reward rules.',
            ],
            'daily_operations' => [
                'Check pending redemptions, available inventory, offer status, and operating notes.',
                'Confirm valid customer reward codes and mark fulfilled redemptions.',
                'Submit or update offers, discounts, and advertising requests for review.',
                'Report stock, service, or campaign issues to the hub manager.',
            ],
        ],
        'internal_sponsor' => [
            'group' => 'external_partner',
            'label' => 'اسپانسر داخلی مکان یا هاب',
            'scope' => 'hub',
            'reports_to' => 'hub_manager',
            'responsibilities' => [
                'Run sponsor activity that belongs to a specific venue or hub management chain.',
                'Submit sponsor rewards, messages, route sponsorship, and display placement requests.',
                'Coordinate activation timing with the relevant hub manager and Exploria approval flow.',
            ],
            'daily_operations' => [
                'Review sponsor placement status, approved creatives, reward stock, and campaign performance.',
                'Respond to hub manager feedback or admin review notes.',
                'Confirm sponsor activation assets are ready for the day.',
                'Record sponsor outcomes and requests for tomorrow.',
            ],
        ],
        'external_sponsor' => [
            'group' => 'external_partner',
            'label' => 'اسپانسر مستقل / بیرونی',
            'scope' => 'region',
            'reports_to' => 'regional_admin',
            'responsibilities' => [
                'Run independent sponsor campaigns that are not owned by one venue or hub.',
                'Submit cross-venue or regional sponsorship requests under platform and regional admin supervision.',
                'Maintain sponsor profile, approved creatives, reward commitments, and reporting expectations.',
            ],
            'daily_operations' => [
                'Review active sponsor campaigns, creative approvals, display placements, and reward usage.',
                'Submit new sponsor requests or requested changes with target region and campaign goals.',
                'Respond to admin notes and upload missing assets or terms.',
                'Check daily sponsor KPIs and settlement-relevant evidence.',
            ],
        ],
        'participant' => [
            'group' => 'public',
            'label' => 'بازدیدکننده / مشارکت‌کننده',
            'scope' => 'team',
            'reports_to' => null,
            'responsibilities' => [
                'Participate in campaigns as an individual, family, or team.',
                'Scan QR codes, complete missions, discover treasures, earn points, and redeem eligible rewards.',
                'Follow campaign rules, consent, privacy, safety, and fair-play requirements.',
            ],
            'daily_operations' => [
                'Start or continue the active campaign journey.',
                'Complete eligible missions and check progress, rewards, and team status.',
                'Redeem approved rewards at participating shops or campaign points.',
                'Report issues, feedback, or lost access through the visitor support flow.',
            ],
        ],
    ],

    'assignment_templates' => [
        [
            'key' => 'ecopark_project_admin',
            'title' => 'مدیر پروژه مکانی اکوپارک',
            'role_key' => 'project_admin',
            'scope_type' => 'venue',
            'scope_code' => 'ecopark-abbasabad',
            'description' => 'برای کاربر داخلی اکسپلوریا که کل اجرای پروژه اکوپارک را مدیریت می‌کند.',
        ],
        [
            'key' => 'ecopark_venue_manager',
            'title' => 'مدیر مکان اکوپارک',
            'role_key' => 'venue_executive',
            'scope_type' => 'venue',
            'scope_code' => 'ecopark-abbasabad',
            'description' => 'برای نماینده مدیریتی خود مکان؛ دسترسی فقط به داده‌های مکان اکوپارک محدود می‌شود.',
        ],
        [
            'key' => 'ecopark_ravaq_manager',
            'title' => 'مدیر رواق تجاری اکوپارک',
            'role_key' => 'ravaq_manager',
            'scope_type' => 'hub',
            'scope_code' => 'ravaq-commercial-hub',
            'description' => 'برای مدیر زون تجاری یا رواق که فروشگاه‌ها و پیشنهادهای تجاری را هماهنگ می‌کند.',
        ],
        [
            'key' => 'ecopark_entry_hub_manager',
            'title' => 'مدیر هاب ورودی اکوپارک',
            'role_key' => 'hub_manager',
            'scope_type' => 'hub',
            'scope_code' => 'visitor-welcome-hub',
            'description' => 'برای مدیر هاب ورودی، راهنمایی بازدیدکننده و کنترل آمادگی شروع تجربه.',
        ],
        [
            'key' => 'cafe_eco_shop_manager',
            'title' => 'مدیر واحد کافه اکو',
            'role_key' => 'shop_manager',
            'scope_type' => 'partner',
            'scope_code' => 'cafe-eco',
            'description' => 'برای مدیر فروشگاه/واحد شریک که پیشنهاد، مصرف کد و موجودی خودش را مدیریت می‌کند.',
        ],
        [
            'key' => 'ecopark_display_manager',
            'title' => 'مدیر تبلیغات و نمایشگرهای اکوپارک',
            'role_key' => 'display_ads_manager',
            'scope_type' => 'venue',
            'scope_code' => 'ecopark-abbasabad',
            'description' => 'تا زمان تکمیل موجودیت شبکه نمایشگر، این قالب نمایشگرها را در سطح مکان اکوپارک محدود می‌کند.',
        ],
    ],
];
